name: publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
  
      # - name: Setup Hugo dependencies for our site
      #   run: sudo apt-get update && sudo apt-get -y install python-docutils python-pygments

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GH_ACTIONS_DEPLOY_KEY_RESUME_RS }}
          external_repository: resume-rs/website
          publish_branch: main
          publish_dir: ./public
          cname: resume.rs
